### ISSUE TITLE
Pretrained Checkpoints are missing.

### ISSUE THREAD

**Issue by yyliu01** [ZhenZHAO/AugSeg#1]
Hi Zhen,

Thanks for your work and the code.
 
The links of pretrained checkpoints (for both resnet50 and resnet101) are incorrect, could you please have a look?
I've tried the checkpoints from CPS (and U2PL), but I've got some _unexpected_keys_ which seem don't appear in your training log.

``` bash
missing_keys:  [] 
unexpected_keys:  ['fc.weight', 'fc.bias']
```

Cheers,
Yuyuan

**Comment by ZhenZHAO** [comment]
Hi Yuyuan, 

Thanks for your reminding. I just updated the links of pre-trained weights.

The warnings like `unexpected_keys` are used for debugging purposes, and they won't affect the performance. You can simply remove/ignore these in the `resnet.py`. 

Please note such warnings are outputted by the `print` function, while the training logs are generated via the interface of `logging`(INFO level by default). Thats why the final training logs have no such warnings. You can check generated logs in your running.

Bests,

**Comment by yyliu01** [comment]
Hi Zhen,

Thanks so much for you feedback.

Cheers,
Yuyuan
