### ISSUE TITLE
测试代码

### ISSUE THREAD

**Issue by FrankYii1** [ZhenZHAO/AugSeg#11]
作者你好！能麻烦你提供一下你的测试代码吗？我想对我自建的数据集进行测试。

**Comment by ZhenZHAO** [comment]
嗯。。。时间有点久了，但应该不难写吧。。。我这有份可视化voc的代码，仅供参考



```python
import logging
import os, sys
import os.path as osp
import time
import numpy as np
from PIL import Image
import yaml
from argparse import ArgumentParser

import torch
import torch.nn.functional as F
import torch.nn.parallel
import torch.optim
import torch.utils.data

from u2pl.models.model_helper import ModelBuilder
from u2pl.utils.utils import convert_state_dict


# # # # # # # # # # # # # # # # # # # # 
# # # # #  1. configurations
# # # # # # # # # # # # # # # # # # # # 
def get_parser():
    parser = ArgumentParser(description="PyTorch Evaluation")
    parser.add_argument("--config", type=str, default="config.yaml")
    parser.add_argument("--gpuid", type=int, default=0)
    parser.add_argument(
        "--model_path",
        type=str,
        default="checkpoints/ckpt_best.pth",
        help="evaluation model path",
    )
    parser.add_argument(
        "--save_folder", type=str, default="viewer", help="results save folder"
    )
    return parser


def get_logger():
    logger_name = "main-logger"
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.INFO)
    handler = logging.StreamHandler()
    fmt = "[%(asctime)s %(levelname)s %(filename)s line %(lineno)d %(process)d] %(message)s"
    handler.setFormatter(logging.Formatter(fmt))
    logger.addHandler(handler)
    return logger


@torch.no_grad()
def net_process(model, image):
    input = image.cuda()
    output, _ = model(input)
    return output

# # # # # # # # # # # # # # # # # # # # 
# # # # #  2. setup colors
# # # # # # # # # # # # # # # # # # # # 
def colorful(mask, colormap):
    color_mask = np.zeros([mask.shape[0], mask.shape[1], 3])
    for i in np.unique(mask):
        color_mask[mask == i] = colormap[i]

    return np.uint8(color_mask)


def create_pascal_label_colormap():
    """Creates a label colormap used in Pascal segmentation benchmark.
    Returns:
        A colormap for visualizing segmentation results.
    """
    colormap = 255 * np.ones((256, 3), dtype=np.uint8)
    colormap[0] = [0, 0, 0]
    colormap[1] = [128, 0, 0]
    colormap[2] = [0, 128, 0]
    colormap[3] = [128, 128, 0]
    colormap[4] = [0, 0, 128]
    colormap[5] = [128, 0, 128]
    colormap[6] = [0, 128, 128]
    colormap[7] = [128, 128, 128]
    colormap[8] = [64, 0, 0]
    colormap[9] = [192, 0, 0]
    colormap[10] = [64, 128, 0]
    colormap[11] = [192, 128, 0]
    colormap[12] = [64, 0, 128]
    colormap[13] = [192, 0, 128]
    colormap[14] = [64, 128, 128]
    colormap[15] = [192, 128, 128]
    colormap[16] = [0, 64, 0]
    colormap[17] = [128, 64, 0]
    colormap[18] = [0, 192, 0]
    colormap[19] = [128, 192, 0]
    colormap[20] = [0, 64, 128]

    return colormap


def main():
    global args, logger, cfg
    args = get_parser().parse_args()

    # setup gpus
    if not isinstance(args.gpuid, int):
        print("please set the gpu id properly")
        sys.exit()
    os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid)
    torch.cuda.set_device('cuda:{}'.format(args.gpuid))

    # setup output folders
    os.makedirs(args.save_folder, exist_ok=True)
    gray_folder = os.path.join(args.save_folder, "gray")
    os.makedirs(gray_folder, exist_ok=True)
    color_folder = os.path.join(args.save_folder, "color")
    os.makedirs(color_folder, exist_ok=True)

    # setup configs
    cfg = yaml.load(open(args.config, "r"), Loader=yaml.Loader)
    logger = get_logger()
    logger.info(args)

    cfg_dset = cfg["dataset"]
    mean, std = cfg_dset["mean"], cfg_dset["std"]
    data_root, f_data_list = cfg_dset["data_root"], cfg_dset["data_list"]
    input_scale = [769, 769] if "cityscapes" in data_root else [513, 513]
    colormap = create_pascal_label_colormap()
    
    # prepare image data
    data_list = []
    if "cityscapes" in data_root:
        for line in open(f_data_list, "r"):
            arr = [
                line.strip(),
                "gtFine/" + line.strip()[12:-15] + "gtFine_labelTrainIds.png",
            ]
            arr = [os.path.join(data_root, item) for item in arr]
            data_list.append(arr)
    else:
        for line in open(f_data_list, "r"):
            arr = [
                "JPEGImages/{}.jpg".format(line.strip()),
                "SegmentationClassAug/{}.png".format(line.strip()),
            ]
            arr = [os.path.join(data_root, item) for item in arr]
            data_list.append(arr)

    # create network and load parameters
    logger.info("=> creating model from '{}' ...".format(args.model_path))
    cfg["net"]["sync_bn"] = False
    model = ModelBuilder(cfg["net"])
    checkpoint = torch.load(args.model_path)
    key = "teacher_state" if "teacher_state" in checkpoint.keys() else "model_state"
    logger.info(f"=> load checkpoint[{key}]")

    saved_state_dict = convert_state_dict(checkpoint[key])
    model.load_state_dict(saved_state_dict, strict=False)
    model.cuda()
    logger.info("Load Model Done!")

    # start evaluating
    model.eval()
    # from tqdm import tqdm
    # for image_path, label_path in tqdm(data_list):
    total_num = len(data_list)
    print_freq = total_num // 12
    print_freq_lst = [i * print_freq for i in range(1,12)]
    print_freq_lst.append(total_num -1)
    for i, (image_path, label_path) in enumerate(data_list):
        # load image
        image_name = image_path.split("/")[-1]
        image = Image.open(image_path).convert("RGB")
        image = np.asarray(image).astype(np.float32)
        
        h, w, _ = image.shape
        
        # image preprocessing
        image /= 255
        image = (image - mean) / std
        image = torch.Tensor(image).permute(2, 0, 1)
        image = image.unsqueeze(dim=0)
        image = F.interpolate(image, input_scale, mode="bilinear", align_corners=True)

        # predict
        output = net_process(model, image)
        output = F.interpolate(output, (h, w), mode="bilinear", align_corners=True)
        mask = torch.argmax(output, dim=1).squeeze().cpu().numpy()

        # save results
        color_mask = Image.fromarray(colorful(mask, colormap))
        color_mask.save(os.path.join(color_folder, image_name))

        mask = Image.fromarray(mask.astype(np.uint8))
        mask.save(os.path.join(gray_folder, image_name))
        if i in print_freq_lst:
            logger.info("====== Processed {}/{} images".format(i+1, total_num))


if __name__ == "__main__":
    main()

```

**Comment by FrankYii1** [comment]
谢谢大佬！！虽然已经解决这个问题，但是还是非常感谢回复，祝科研高产！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhenZHAO/AugSeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月15日(星期二) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhenZHAO/AugSeg] 测试代码 (Issue #11)





 
嗯。。。时间有点久了，但应该不难写吧。。。我这有份可视化voc的代码，仅供参考
 import logging import os, sys import os.path as osp import time import numpy as np from PIL import Image import yaml from argparse import ArgumentParser import torch import torch.nn.functional as F import torch.nn.parallel import torch.optim import torch.utils.data from u2pl.models.model_helper import ModelBuilder from u2pl.utils.utils import convert_state_dict # # # # # # # # # # # # # # # # # # # #  # # # # #  1. configurations # # # # # # # # # # # # # # # # # # # #  def get_parser():     parser = ArgumentParser(description="PyTorch Evaluation")     parser.add_argument("--config", type=str, default="config.yaml")     parser.add_argument("--gpuid", type=int, default=0)     parser.add_argument(         "--model_path",         type=str,         default="checkpoints/ckpt_best.pth",         help="evaluation model path",     )     parser.add_argument(         "--save_folder", type=str, default="viewer", help="results save folder"     )     return parser def get_logger():     logger_name = "main-logger"     logger = logging.getLogger(logger_name)     logger.setLevel(logging.INFO)     handler = logging.StreamHandler()     fmt = "[%(asctime)s %(levelname)s %(filename)s line %(lineno)d %(process)d] %(message)s"     handler.setFormatter(logging.Formatter(fmt))     logger.addHandler(handler)     return logger @torch.no_grad() def net_process(model, image):     input = image.cuda()     output, _ = model(input)     return output # # # # # # # # # # # # # # # # # # # #  # # # # #  2. setup colors # # # # # # # # # # # # # # # # # # # #  def colorful(mask, colormap):     color_mask = np.zeros([mask.shape[0], mask.shape[1], 3])     for i in np.unique(mask):         color_mask[mask == i] = colormap[i]     return np.uint8(color_mask) def create_pascal_label_colormap():     """Creates a label colormap used in Pascal segmentation benchmark.     Returns:         A colormap for visualizing segmentation results.     """     colormap = 255 * np.ones((256, 3), dtype=np.uint8)     colormap[0] = [0, 0, 0]     colormap[1] = [128, 0, 0]     colormap[2] = [0, 128, 0]     colormap[3] = [128, 128, 0]     colormap[4] = [0, 0, 128]     colormap[5] = [128, 0, 128]     colormap[6] = [0, 128, 128]     colormap[7] = [128, 128, 128]     colormap[8] = [64, 0, 0]     colormap[9] = [192, 0, 0]     colormap[10] = [64, 128, 0]     colormap[11] = [192, 128, 0]     colormap[12] = [64, 0, 128]     colormap[13] = [192, 0, 128]     colormap[14] = [64, 128, 128]     colormap[15] = [192, 128, 128]     colormap[16] = [0, 64, 0]     colormap[17] = [128, 64, 0]     colormap[18] = [0, 192, 0]     colormap[19] = [128, 192, 0]     colormap[20] = [0, 64, 128]     return colormap def main():     global args, logger, cfg     args = get_parser().parse_args()     # setup gpus     if not isinstance(args.gpuid, int):         print("please set the gpu id properly")         sys.exit()     os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid)     torch.cuda.set_device('cuda:{}'.format(args.gpuid))     # setup output folders     os.makedirs(args.save_folder, exist_ok=True)     gray_folder = os.path.join(args.save_folder, "gray")     os.makedirs(gray_folder, exist_ok=True)     color_folder = os.path.join(args.save_folder, "color")     os.makedirs(color_folder, exist_ok=True)     # setup configs     cfg = yaml.load(open(args.config, "r"), Loader=yaml.Loader)     logger = get_logger()     logger.info(args)     cfg_dset = cfg["dataset"]     mean, std = cfg_dset["mean"], cfg_dset["std"]     data_root, f_data_list = cfg_dset["data_root"], cfg_dset["data_list"]     input_scale = [769, 769] if "cityscapes" in data_root else [513, 513]     colormap = create_pascal_label_colormap()          # prepare image data     data_list = []     if "cityscapes" in data_root:         for line in open(f_data_list, "r"):             arr = [                 line.strip(),                 "gtFine/" + line.strip()[12:-15] + "gtFine_labelTrainIds.png",             ]             arr = [os.path.join(data_root, item) for item in arr]             data_list.append(arr)     else:         for line in open(f_data_list, "r"):             arr = [                 "JPEGImages/{}.jpg".format(line.strip()),                 "SegmentationClassAug/{}.png".format(line.strip()),             ]             arr = [os.path.join(data_root, item) for item in arr]             data_list.append(arr)     # create network and load parameters     logger.info("=&gt; creating model from '{}' ...".format(args.model_path))     cfg["net"]["sync_bn"] = False     model = ModelBuilder(cfg["net"])     checkpoint = torch.load(args.model_path)     key = "teacher_state" if "teacher_state" in checkpoint.keys() else "model_state"     logger.info(f"=&gt; load checkpoint[{key}]")     saved_state_dict = convert_state_dict(checkpoint[key])     model.load_state_dict(saved_state_dict, strict=False)     model.cuda()     logger.info("Load Model Done!")     # start evaluating     model.eval()     # from tqdm import tqdm     # for image_path, label_path in tqdm(data_list):     total_num = len(data_list)     print_freq = total_num // 12     print_freq_lst = [i * print_freq for i in range(1,12)]     print_freq_lst.append(total_num -1)     for i, (image_path, label_path) in enumerate(data_list):         # load image         image_name = image_path.split("/")[-1]         image = Image.open(image_path).convert("RGB")         image = np.asarray(image).astype(np.float32)                  h, w, _ = image.shape                  # image preprocessing         image /= 255         image = (image - mean) / std         image = torch.Tensor(image).permute(2, 0, 1)         image = image.unsqueeze(dim=0)         image = F.interpolate(image, input_scale, mode="bilinear", align_corners=True)         # predict         output = net_process(model, image)         output = F.interpolate(output, (h, w), mode="bilinear", align_corners=True)         mask = torch.argmax(output, dim=1).squeeze().cpu().numpy()         # save results         color_mask = Image.fromarray(colorful(mask, colormap))         color_mask.save(os.path.join(color_folder, image_name))         mask = Image.fromarray(mask.astype(np.uint8))         mask.save(os.path.join(gray_folder, image_name))         if i in print_freq_lst:             logger.info("====== Processed {}/{} images".format(i+1, total_num)) if __name__ == "__main__":     main()

**Comment by Liumomo30** [comment]
> 谢谢大佬！！虽然已经解决这个问题，但是还是非常感谢回复，祝科研高产！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZhenZHAO/AugSeg" ***@***.***&gt;; 发送时间:&nbsp;2023年8月15日(星期二) 中午11:41 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ZhenZHAO/AugSeg] 测试代码 (Issue #11) 嗯。。。时间有点久了，但应该不难写吧。。。我这有份可视化voc的代码，仅供参考 import logging import os, sys import os.path as osp import time import numpy as np from PIL import Image import yaml from argparse import ArgumentParser import torch import torch.nn.functional as F import torch.nn.parallel import torch.optim import torch.utils.data from u2pl.models.model_helper import ModelBuilder from u2pl.utils.utils import convert_state_dict # # # # # # # # # # # # # # # # # # # # # # # # # 1. configurations # # # # # # # # # # # # # # # # # # # # def get_parser(): parser = ArgumentParser(description="PyTorch Evaluation") parser.add_argument("--config", type=str, default="config.yaml") parser.add_argument("--gpuid", type=int, default=0) parser.add_argument( "--model_path", type=str, default="checkpoints/ckpt_best.pth", help="evaluation model path", ) parser.add_argument( "--save_folder", type=str, default="viewer", help="results save folder" ) return parser def get_logger(): logger_name = "main-logger" logger = logging.getLogger(logger_name) logger.setLevel(logging.INFO) handler = logging.StreamHandler() fmt = "[%(asctime)s %(levelname)s %(filename)s line %(lineno)d %(process)d] %(message)s" handler.setFormatter(logging.Formatter(fmt)) logger.addHandler(handler) return logger @torch.no_grad() def net_process(model, image): input = image.cuda() output, _ = model(input) return output # # # # # # # # # # # # # # # # # # # # # # # # # 2. setup colors # # # # # # # # # # # # # # # # # # # # def colorful(mask, colormap): color_mask = np.zeros([mask.shape[0], mask.shape[1], 3]) for i in np.unique(mask): color_mask[mask == i] = colormap[i] return np.uint8(color_mask) def create_pascal_label_colormap(): """Creates a label colormap used in Pascal segmentation benchmark. Returns: A colormap for visualizing segmentation results. """ colormap = 255 * np.ones((256, 3), dtype=np.uint8) colormap[0] = [0, 0, 0] colormap[1] = [128, 0, 0] colormap[2] = [0, 128, 0] colormap[3] = [128, 128, 0] colormap[4] = [0, 0, 128] colormap[5] = [128, 0, 128] colormap[6] = [0, 128, 128] colormap[7] = [128, 128, 128] colormap[8] = [64, 0, 0] colormap[9] = [192, 0, 0] colormap[10] = [64, 128, 0] colormap[11] = [192, 128, 0] colormap[12] = [64, 0, 128] colormap[13] = [192, 0, 128] colormap[14] = [64, 128, 128] colormap[15] = [192, 128, 128] colormap[16] = [0, 64, 0] colormap[17] = [128, 64, 0] colormap[18] = [0, 192, 0] colormap[19] = [128, 192, 0] colormap[20] = [0, 64, 128] return colormap def main(): global args, logger, cfg args = get_parser().parse_args() # setup gpus if not isinstance(args.gpuid, int): print("please set the gpu id properly") sys.exit() os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid) torch.cuda.set_device('cuda:{}'.format(args.gpuid)) # setup output folders os.makedirs(args.save_folder, exist_ok=True) gray_folder = os.path.join(args.save_folder, "gray") os.makedirs(gray_folder, exist_ok=True) color_folder = os.path.join(args.save_folder, "color") os.makedirs(color_folder, exist_ok=True) # setup configs cfg = yaml.load(open(args.config, "r"), Loader=yaml.Loader) logger = get_logger() logger.info(args) cfg_dset = cfg["dataset"] mean, std = cfg_dset["mean"], cfg_dset["std"] data_root, f_data_list = cfg_dset["data_root"], cfg_dset["data_list"] input_scale = [769, 769] if "cityscapes" in data_root else [513, 513] colormap = create_pascal_label_colormap() # prepare image data data_list = [] if "cityscapes" in data_root: for line in open(f_data_list, "r"): arr = [ line.strip(), "gtFine/" + line.strip()[12:-15] + "gtFine_labelTrainIds.png", ] arr = [os.path.join(data_root, item) for item in arr] data_list.append(arr) else: for line in open(f_data_list, "r"): arr = [ "JPEGImages/{}.jpg".format(line.strip()), "SegmentationClassAug/{}.png".format(line.strip()), ] arr = [os.path.join(data_root, item) for item in arr] data_list.append(arr) # create network and load parameters logger.info("=&gt; creating model from '{}' ...".format(args.model_path)) cfg["net"]["sync_bn"] = False model = ModelBuilder(cfg["net"]) checkpoint = torch.load(args.model_path) key = "teacher_state" if "teacher_state" in checkpoint.keys() else "model_state" logger.info(f"=&gt; load checkpoint[{key}]") saved_state_dict = convert_state_dict(checkpoint[key]) model.load_state_dict(saved_state_dict, strict=False) model.cuda() logger.info("Load Model Done!") # start evaluating model.eval() # from tqdm import tqdm # for image_path, label_path in tqdm(data_list): total_num = len(data_list) print_freq = total_num // 12 print_freq_lst = [i * print_freq for i in range(1,12)] print_freq_lst.append(total_num -1) for i, (image_path, label_path) in enumerate(data_list): # load image image_name = image_path.split("/")[-1] image = Image.open(image_path).convert("RGB") image = np.asarray(image).astype(np.float32) h, w, _ = image.shape # image preprocessing image /= 255 image = (image - mean) / std image = torch.Tensor(image).permute(2, 0, 1) image = image.unsqueeze(dim=0) image = F.interpolate(image, input_scale, mode="bilinear", align_corners=True) # predict output = net_process(model, image) output = F.interpolate(output, (h, w), mode="bilinear", align_corners=True) mask = torch.argmax(output, dim=1).squeeze().cpu().numpy() # save results color_mask = Image.fromarray(colorful(mask, colormap)) color_mask.save(os.path.join(color_folder, image_name)) mask = Image.fromarray(mask.astype(np.uint8)) mask.save(os.path.join(gray_folder, image_name)) if i in print_freq_lst: logger.info("====== Processed {}/{} images".format(i+1, total_num)) if __name__ == "__main__": main() — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
> ------------------ 原始邮件 ------------------ 发件人: "ZhenZHAO/AugSeg" ***@***.***>; 发送时间: 2023年8月15日(星期二) 中午11:41 ***@***.***>; **@***.******@***.***>; 主题: Re: [ZhenZHAO/AugSeg] 测试代码（问题 #11 ） 嗯。。。时间有点久了，不过应该不难写吧。。。我这有份可视化voc的代码，仅供参考 导入日志记录导入os，sys导入os.path作为osp导入时间导入numpy作为np从PIL导入图像导入yaml从argparse导入ArgumentParser导入torch导入torch.nn.function作为F导入torch.nn.parallel导入torch.optim导入torch .utils.data from u2pl.models.model_helper import ModelBuilder from u2pl.utils.utils import conversion_state_dict # # # # # # # # # # # # # # # # # # # # # # # # 1. 配置 # # # # # # # # # # # # # # # # # # # def get_parser(): parser = ArgumentParser(description="PyTorch Evaluation") parser.add_argument("--config", type=str, default= "config.yaml") parser.add_argument("--gpuid", type=int, default=0) parser.add_argument("--model_path", type=str, default="checkpoints/ckpt_best.pth", help= "评估模型路径", ) parser.add_argument( "--save_folder", type=str, default="viewer", help="结果保存文件夹" ) return parser def get_logger(): logger_name = "main-logger" logger =logging.getLogger(logger_name) logger.setLevel(logging.INFO) handler =logging.StreamHandler() fmt = "[%(asctime)s %(levelname)s %(文件名)s 行 %(lineno)d %(进程)d] %(message)s" handler.setFormatter(logging.Formatter(fmt)) logger.addHandler(handler) return logger @torch.no_grad() def net_process(model, image): input = image.cuda() 输出, _ = model(输入) 返回输出 # # # # # # # # # # # # # # # # # # # # # # # # 2. 设置颜色 # # # # # # # # # # # # # # # # # # # # def color(mask, colormap): color_mask = np.zeros([mask.shape[0], mask.shape[1], 3]) for i in np.unique(mask): color_mask[mask == i] = colormap[i] 返回 np.uint8(color_mask) def create_pascal_label_colormap(): """创建 Pascal 分割基准中使用的标签颜色图。返回：用于可视化分割结果的颜色图。 """ colormap = 255 * np.ones((256, 3), dtype= np.uint8) 颜色图[0] = [0, 0, 0] 颜色图[1] = [128, 0, 0] 颜色图[2] = [0, 128, 0] 颜色图[3] = [128, 128, 0] 颜色图[4] = [0, 0, 128] 颜色图[5] = [128, 0, 128] 颜色图[6] = [0, 128, 128] 颜色图[7] = [128, 128, 128]颜色图[8] = [64, 0, 0] 颜色图[9] = [192, 0, 0] 颜色图[10] = [64, 128, 0] 颜色图[11] = [192, 128, 0] 颜色图[ 12] = [64, 0, 128] 颜色图[13] = [192, 0, 128] 颜色图[14] = [64, 128, 128] 颜色图[15] = [192, 128, 128] 颜色图[16] = [0, 64, 0] 颜色图[17] = [128, 64, 0] 颜色图[18] = [0, 192, 0] 颜色图[19] = [128, 192, 0] 颜色图[20] = [ 0, 64, 128] return colormap def main(): global args, logger, cfg args = get_parser().parse_args() # 设置 GPU if not isinstance(args.gpuid, int): print("请设置 GPU id正确") sys.exit() os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpuid) torch.cuda.set_device('cuda:{}'.format(args.gpuid)) # 设置输出文件夹 os.makedirs （args.save_folder，exist_ok = True）gray_folder = os.path.join（args.save_folder，“灰色”）os.makedirs（gray_folder，exist_ok = True）color_folder = os.path.join（args.save_folder，“颜色” ) os.makedirs(color_folder, exit_ok=True) # 设置配置 cfg = yaml.load(open(args.config, "r"), Loader=yaml.Loader) logger = get_logger() logger.信息（args）cfg_dset = cfg [“数据集”]平均值，std = cfg_dset [“平均值”]，cfg_dset [“std”] data_root，f_data_list = cfg_dset [“data_root”]，cfg_dset [“data_list”] input_scale = [769 , 769] if "cityscapes" in data_root else [513, 513] colormap = create_pascal_label_colormap() # 准备图像数据 data_list = [] if "cityscapes" in data_root: for line in open(f_data_list, "r"): arr = [ line.strip(), "gtFine/" + line.strip()[12:-15] + "gtFine_labelTrainIds.png", ] arr = [os.path.join(data_root, item) for item in arr] data_list.追加(arr) else: for line in open(f_data_list, "r"): arr = [ "JPEGImages/{}.jpg".format(line.strip()), "SegmentationClassAug/{}.png".format( line.strip()), ] arr = [os.path.join(data_root, item) for item in arr] data_list.append(arr) # 创建网络并加载参数 logger.info("=> 创建模型 from '{ }' ...".format(args.model_path)) cfg["net"]["sync_bn"] = False model = ModelBuilder(cfg["net"]) checkpoint = torch.load(args.model_path) key = "teacher_state" if "teacher_state" in checkpoint.keys() else "model_state" logger.info(f"=> load checkpoint[{key}]") saving_state_dict = Convert_state_dict(checkpoint[key]) model.load_state_dict(saved_state_dict, strict =False) model.cuda() logger.info("加载模型完成！") # 开始评估 model.eval() # from tqdm import tqdm # for image_path, label_path in tqdm(data_list):total_num = len(data_list) print_freq =total_num // 12 print_freq_lst = [i * print_freq for i in range(1,12)] print_freq_lst.append(total_num -1) for i, (image_path, label_path) in enumerate(data_list): # 加载图像 image_name = image_path.split("/")[-1] image = Image.open(image_path).convert("RGB ") image = np.asarray(image).astype(np.float32) h, w, _ = image.shape # 图像预处理 image /= 255 image = (image -mean) / std image = torch.Tensor(image) .permute(2, 0, 1) image = image.unsqueeze(dim=0) image = F.interpolate(image, input_scale, mode="bilinear",align_corners=True) # 预测输出 = net_process(model, image) 输出= F.interpolate(output, (h, w), mode="bilinear",align_corners=True) mask = torch.argmax(output, dim=1).squeeze().cpu().numpy() # 保存结果color_mask = Image.fromarray(colorful(mask, colormap)) color_mask.save(os.path.join(color_folder, image_name)) mask = Image.fromarray(mask.astype(np.uint8)) mask.save(os.path .join(gray_folder, image_name)) 如果我在 print_freq_lst: logger.info("====== 已处理的 {}/{} 图像"。格式(i+1,total_num)) if __name__ == "__main__": main() — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。 您收到此消息是因为您创作了该主题。消息 ID：***@***.***>

您好！请问可以分享一下可视化测试集掩码的代码嘛，感谢回复！
