### ISSUE TITLE
关于结果复现

### ISSUE THREAD

**Issue by aikx** [ZhenZHAO/AugSeg#13]
您好！感谢您的出色工作！
我在使用源代码复现时，发现resnet-101下voc fine 92labeled配置只跑出了63.5的MIoU，显著低于原论文汇报的71.09，我使用的config是training log下相同实验的yaml文件，请问是哪里出了差错吗？另外，同样方式183labeled设置是可以复现结果的。
谢谢！

**Comment by ZhenZHAO** [comment]
Should not.. Can you  provide the training log with first several epochs, and detail your training env like the GPU, bz, etc.

**Comment by aikx** [comment]
> Should not.. Can you provide the training log with first several epochs, and detail your training env like the GPU, bz, etc.
python 3.7.4 torch 1.12.1+cu116 NVIDIA 3090x2
more details in training log:
[seg_2023-09-16_16_57_54.log](https://github.com/ZhenZHAO/AugSeg/files/12642457/seg_2023-09-16_16_57_54.log)

**Comment by aikx** [comment]
> Should not.. Can you provide the training log with first several epochs, and detail your training env like the GPU, bz, etc.

python 3.7.4 torch 1.12.1+cu116 NVIDIA 3090x2
more details in training log:
[seg_2023-09-16_16_57_54.log](https://github.com/ZhenZHAO/AugSeg/files/12642457/seg_2023-09-16_16_57_54.log)

**Comment by aikx** [comment]
> Should not.. Can you provide the training log with first several epochs, and detail your training env like the GPU, bz, etc.

python 3.7.4 torch 1.12.1+cu116 NVIDIA 3090x2
more details in training log:
[seg_2023-09-16_16_57_54.log](https://github.com/ZhenZHAO/AugSeg/files/12642464/seg_2023-09-16_16_57_54.log)

**Comment by ZhenZHAO** [comment]
Hi, I found some new param under the "strong augs", like the p:0.2, ada:True？

I have no idea about the "ada", but if you apply my revised strong augmentation with 0.2 prob, you definitely get lower results with scarce labels.

Logic is like this, I have already revised the strong aug into much soft ones, like the continuous, like the random. You can directly apply it with prob of 1.0. It is safe.

BTW, if I remember correctly, you can apply more strong augmentation on scarce cases like 92, and higher results can be easily obtained. In this version, I did not adjust these things, cuz I just wanna make everything simple and consist.

**Comment by ZhenZHAO** [comment]
![image](https://github.com/ZhenZHAO/AugSeg/assets/13755409/8c26bf6a-d75a-4ed4-96a7-4dc363b5320f)

**Comment by aikx** [comment]
感谢您的纠正！确实是我工作的失误，这里我降低了strong aug的强度，导致了结果变差，实际上是可以复现的。但有趣的一点是，在有标注数据较为稀缺的时候，一般直觉地认为伪标签的质量更低，那么更强的strong aug可能会加剧这一现象，例如破坏数据分布等，但实验结果似乎相反？另外，似乎在您提供的training log中也出现了稀少标注时训练后期结果变差的问题，对此您是否有解释呢？
谢谢！

**Comment by ZhenZHAO** [comment]
- 产生pseudo-label的是teacher, teacher 不直接受 strong aug的影响。如何进一步弱化这个影响呢？另一个简单的思路，refer to https://github.com/ZhenZHAO/DPMS. 
- 
- Semi里，我个人喜欢强调，使用aug的目的是产生prediction disagreement，但也不能忽视aug最原本的目的，扩宽数据分析。我这已经是往random，continuous调弱很多了，你再弄个0.2，当然不够看的。97个label，就算不用unlabel，你用aug玩玩supervised也会涨的。再多的解释可能需要您能自己挖掘了。
- 
- 半监督里，discrimination的能力只能从label里学到，当标签非常少的情况下，barley supervised, 那么性能很受unlabeled data的影响，轮次越多越容易过拟合到noisy上去，少标签分类，分割，都会出现后期性能差的情况。如果想处理这个case，加点unsupervised的auxiliary task，就会好一些，这工作并不打算往那路子走。

BTW， 您最后传的log删掉了您修改的部分？？ 我希望你把这个issue的title也改一下，太不友好了  ^ ^, 这工作还是很容易复现甚至拿到更高的性能的。

**Comment by aikx** [comment]
感谢回复！当时是错误地认为该设置在代码中并不生效，于是为了避免误解便删掉了，但后期发现还是被影响了，是实现的失误。已经修改title，再次感谢您的回复，祝科研顺利xd
