### ISSUE TITLE
关于分布式训练的问题

### ISSUE THREAD

**Issue by Secret813** [ZhenZHAO/AugSeg#14]
您好，我想问一下您这个项目是否默认为单机单卡训练，如果是分布式多机训练的话，能否改为普通单机单卡训练呢，具体的操作如何实现？

**Comment by ZhenZHAO** [comment]
from previous issue, https://github.com/ZhenZHAO/AugSeg/issues/3

"Hi, 默认设置不再过一次weak label去稳定的情况下，2张卡V100/A100 跑VOC实验 （r50: 17G, r101: 21G），4张V100/A100 跑Citys 实验 (r50:20G, r101: 25G). 我提供的log应该是，在CVPR23前一两周全部在A100上跑的结果。"

单张卡跑不了吧，，除非80GA100？

**Comment by Secret813** [comment]
您好，这个意思是默认为单机训练嘛，因为没有条件进行分布式训练，多卡是可以的

**Comment by ZhenZHAO** [comment]
默认用的是DDP， 设置一下都能跑。只要显存能发的下就行。

**Comment by Secret813** [comment]
我想问一下，具体如何更改设置来进行单机训练呢？麻烦您啦

**Comment by ZhenZHAO** [comment]
? 默认的就是单机多卡，直接跑呀？都是DDP设置的。在`scripts`里有我跑的脚本

**Comment by Secret813** [comment]
好的，十分感谢！
