### ISSUE TITLE
关于Adaptive CutMix-based augmentations的设计

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/AugSeg#16]
你好！想问一个关于论文技术的问题，就是Adaptive CutMix-based augmentations这一个过程你是怎么思考并设计的？如果我是作者，我需要怎样才能自然地设计出这个组件呢？谢谢！

**Comment by dhh123hh** [comment]
你好，本文的Adaptive Label-aided CutMix一共有三步，第二步已经利用pi进行了一次cutMix，为什么还又在第三步再cutMix

**Comment by ZhenZHAO** [comment]
We talked a lot. Good Luck man!
