### ISSUE TITLE
关于Adaptive Label-aided CutMix第三步的疑问

### ISSUE THREAD

**Issue by dhh123hh** [ZhenZHAO/AugSeg#18]
你好，本文的Adaptive Label-aided CutMix一共有三步，第二步已经利用pi进行了一次cutMix，为什么还又在第三步再cutMix，这样设计是有什么想法吗

**Comment by ZhenZHAO** [comment]
我记得是，1)为了增大随机性。2）为了防止过拟合到labeled data上。
