### ISSUE TITLE
Cityscapes 数据集上配置的问题

### ISSUE THREAD

**Issue by syqisme** [ZhenZHAO/AugSeg#19]
作者您好，最近我在您的项目上进行修改学习，目前在pascal voc 2012 数据集上的效果良好，可是在Cityscapes数据集上的效果很差，我仔细研究了您所展示的配置文件以及实验日志，但是目前问题也没有解决，于是想来问一下关于这个数据集上有什么需要注意的地方？首先在这个数据集上损失计算使用了ohem损失，在计算损失中没有用到辅助损失以及类别的权重。然后我注意到同样batch×gpu数目下这个数据集的学习率扩大了10倍，在训练轮次上也调整到了240轮，类别数目为19。除此之外，在评估过程中使用了滑动窗口评估。注意到了这些问题后，我的模型在cityscapes数据集上效果还是很差，目前这个阶段遇到这个问题很困惑不知如何解决。可以给我一些建议吗？如果可以的话真的非常感谢！

**Comment by syqisme** [comment]
作者您好，最近我在您的项目上进行修改学习，目前在pascal voc 2012 数据集上的效果良好，可是在Cityscapes数据集上的效果很差，我仔细研究了您所展示的配置文件以及实验日志，但是目前问题也没有解决，于是想来问一下关于这个数据集上有什么需要注意的地方？首先在这个数据集上损失计算使用了ohem损失，在计算损失中没有用到辅助损失以及类别的权重。然后我注意到同样batch×gpu数目下这个数据集的学习率扩大了10倍，在训练轮次上也调整到了240轮，类别数目为19。除此之外，在评估过程中使用了滑动窗口评估。注意到了这些问题后，我的模型在cityscapes数据集上效果还是很差，目前这个阶段遇到这个问题很困惑不知如何解决。可以给我一些建议吗？如果可以的话真的非常感谢！

**Comment by ZhenZHAO** [comment]
Augseg因为简单，在citys上更有优势。你方便发给我一份你的训练log，我看一下，说一下你的GPU设置。我那些训练log前面就是完整的参数配置了。

**Comment by syqisme** [comment]
作者您好，十分感写您的回复，目前我的问题已经解决，我是根据你的思想自己重写的代码，并在其基础上进行改进，你的代码给了我很大的启发。

**Comment by syqisme** [comment]
作者您好，十分感写您的回复，我当时是自己重写的代码，一些细节上的问题没有注意，目前问题已经解决，您的工作给了我很大启发，谢谢！
