### ISSUE TITLE
关于过早达到最高iou的问题

### ISSUE THREAD

**Issue by RzzzLiu** [ZhenZHAO/AugSeg#21]
作者您好，非常感谢你的工作。我发现您的iters好像较其他的工作更多一些，所以这是否会收敛的更快一些，我跑别的代码大概4 50轮才收敛，您的大概的20多轮就收敛了，这是否是因为iters更多的原因

**Comment by 79zzz** [comment]
您好，请问您跑通了这个代码吗？能否将您复现后的代码分享给我

**Comment by RzzzLiu** [comment]
> 您好，请问您跑通了这个代码吗？能否将您复现后的代码分享给我

 不用复现吧，这个代码可以直接跑呀，这个作者写的挺好的，你直接根据他的指示跑就可以了

**Comment by RzzzLiu** [comment]
> 因为我遇到了一个如上的错误一直没有修改好，所以想看看大家修改完后和我的区别在哪
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年2月24日(星期六) 上午10:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ZhenZHAO/AugSeg] 关于过早达到最高iou的问题 (Issue #21) 您好，请问您跑通了这个代码吗？能否将您复现后的代码分享给我 不用复现吧，这个代码可以直接跑呀，这个作者写的挺好的，你直接根据他的指示跑就可以了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你遇到的那个问题应该是你指定GPU的问题，这个不是代码的问题，你可以把你的错误复制问问chatgpt或者new bing

**Comment by 79zzz** [comment]
gpt和网上的答案说可能是由于索引超过数组的界限或者是标签数量和模型最后的线性层不匹配

**Comment by RzzzLiu** [comment]
> gpt和网上的答案说可能是由于索引超过数组的界限或者是标签数量和模型最后的线性层不匹配

不对吧，我看你那个提问似乎是gpu指定的问题。至于索引，应该和类别有关，我用这个模型跑的也是别的数据集，跑了好几个都没问题，我没做任何改动，只改了类别数目和图片size，batchsize这些

**Comment by 79zzz** [comment]
谢谢！那我再去仔细检查一遍

**Comment by RzzzLiu** [comment]
> 谢谢！那我再去仔细检查一遍

没事，也可能是你的数据集的问题，你最好把数据集的标签索引从0开始

**Comment by RzzzLiu** [comment]
> 数据集我用的就是pascal voc2012的

那就不知道了，我用包括pascal在内，好几个数据集都跑通了

**Comment by 79zzz** [comment]
我这几天尝试换服务器跑以及升级cuda后还是无法解决这个问题，希望您可以分享一下您修改后的代码，我仔细对照看看哪个环节有问题
