### ISSUE TITLE
关于实验设置

### ISSUE THREAD

**Issue by yang654123** [ZhenZHAO/AugSeg#3]
你好我想请问一下，您再跑实验的时候使用的是几张卡，是什么类型的卡呀

**Comment by ZhenZHAO** [comment]
Hi, 默认设置不再过一次weak label去稳定的情况下，2张卡V100/A100 跑VOC实验 （r50: 17G, r101: 21G），4张V100/A100 跑Citys 实验 (r50:20G, r101: 25G). 我提供的log应该是，在CVPR23前一两周全部在A100上跑的结果。

希望对您有用~

**Comment by s07362022** [comment]
想請問一下有沒有不用dist跑的版本呢?
