### ISSUE TITLE
VOC 文件

### ISSUE THREAD

**Issue by zifuwanggg** [ZhenZHAO/AugSeg#5]
Pascal: [JPEGImages](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar) | [SegmentationClass](https://drive.google.com/file/d/1ikrDlsai5QSf2GiSUR3f8PZUzyTubcuF/view?usp=sharing)

其中[JPEGImages](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar)下载并解压后是
```
VOCdevkit
  --VOC2012
    --JPEGImages
    --SegmentationClass
```
[SegmentationClass](https://drive.google.com/file/d/1ikrDlsai5QSf2GiSUR3f8PZUzyTubcuF/view?usp=sharing)下载并解压后是
```
SegmentationClass/
```

而你提供的文件路径为

    ├── VOC2012
    	├── JPEGImages
    	├── SegmentationClass
    	└── SegmentationClassAug

请问我应该把哪个重新命名为SegmentationClassAug？

**Comment by ZhenZHAO** [comment]
哎呦，不好意思，我应该是用的第二个。 

Here is the link with all the files I used to train VOC，
https://drive.google.com/file/d/1bije-iFauLwzTRH_JLT7KaSiBcRpqhrZ/view

至于命名怎么样都行，代码里 https://github.com/ZhenZHAO/AugSeg/blob/main/augseg/dataset/base.py#L27，是写的SegmentationClassAug，重名一下或者改这的名称就行。

**Comment by zifuwanggg** [comment]
谢谢回复！还有一个就是我看到你的`config.yaml`里写了`# <<abl1-threshold>>: [0.7, 0.75, 0.8, 0.85, 0.9, 0.95]`，但在paper里好像没见到相关的实验结果。请问能麻烦提供一下吗？

**Comment by ZhenZHAO** [comment]
不好意思，现在手边没资源，这个ablation没法提供了。但是我可以roughly说一下这个参数。半监督里，用这么个阈值来做一次伪标签的过滤(filtering) 是老故事了，简单，有效。但是这个参数确实和数据集十分相关。

- trade-off。 做pseudo的选择就是为了提高pseudo-label的正确性，但是这样会导致参与训练的unlabel data数量减少。我记得我很早在LaSSL这文章里也聊过，数量和质量的trade-off。

- 如果数据集比较简单，比如分类的 cifar，mnist，分割的voc数据集，从fixmatch开始，就一直用0.95，真的是祖传的超参了。逻辑就是，简单数据集，高置信度的伪标签数量会很快涨上去，所以这类数据集上，其实就更关注 pseudo的质量。

- 如果数据集比较难，比如分类的imagent，分割的citys数据集，那么故事就不同了。如果阈值过高，过分强调质量，会导致unlabel data参与训练的太少。这时候就要相对关注一下，伪标签的数量，降低阈值，甚至不用阈值。

所以其实，这个ablation，结果是几乎是可以预期到的。我在另一个分割的工作imas里做了threshold 的abaltion，可以参考一下。不论分类分割，其实逻辑是一样的。对这个 pseudo的质量和数量，多记录一下，

- 这一类的工作，逻辑都是一样的，各种pseudo-rectifiying 的工作，关注pseudo的正确性，都可以和threshold这一操作类比，比如你去feature 上，或者再做一个解耦的分类器去再产生一个pseudo，两个甚至多个预测emsemble一下，都可以提升pseudo的正确性，所以VOC上提点不难。当然，代价就是会复杂起来。

- 当然也可以和别的问题结合，比如分割问题都是长尾的，你可以用多个threshold，而不是用一个。我不喜欢这个路子，但是确实会有效的，特别拿一些先验信息进来用。

- 那如何提升unlabel data的利用率呢，不被threshold这一下约束住。最简单直接的方式，就是做一个无监督的辅助任务，比如对比学习，这一类本来就不需要label，所以故事可以各种聊，但是效果肯定不如从pseudo的正确性入手。。。个人不喜欢这一类工作，但是貌似很多。


希望对您有帮助，我自己也记录一下 ^ ^

**Comment by zifuwanggg** [comment]
非常感谢，简直太有帮助了！

**Comment by aikx** [comment]
您好！请问为什么我看见citys的yaml中设置的threshold为-0.7呢，似乎是放弃了用阈值过滤伪标签？

**Comment by ZhenZHAO** [comment]
From my previous explanation: "如果数据集比较难，比如分类的imagent，分割的citys数据集，那么故事就不同了。如果阈值过高，过分强调质量，会导致unlabel data参与训练的太少。这时候就要相对关注一下，伪标签的数量，降低阈值，甚至不用阈值。"

可以跑实验玩一下看看
