### ISSUE TITLE
关于最终结果和模型保存

### ISSUE THREAD

**Issue by chen-r9** [ZhenZHAO/AugSeg#7]
最后使用的结果值是用teacher验证的MIOU,那是不是说明保存的checkpoint不应该是student而应该是teacher？

**Comment by ZhenZHAO** [comment]
??? I did not get your point. 

In this version of code, https://github.com/ZhenZHAO/AugSeg/blob/main/train_semi.py#L219, I saved the best teacher.

But, certainly, you can save whatever you want, just a few line of code.
