### ISSUE TITLE
学生模型比教师模型好

### ISSUE THREAD

**Issue by jjjsyyy** [ZhenZHAO/AugSeg#9]
我在实验过程中发现您的代码中输出的stu的iou比tea高，请问您有出现这种情况吗？

**Comment by ZhenZHAO** [comment]
哎呦，是的。但是不会差的太多，你看我提供的log里，也是有student比teacher好的情况。我的理解
- 但是一般这种情况发生在简单的数据集上，比如分类的cifar，分割的VOC。但是对那些类别多，比较challenge的情况，比如分类的imagenet，和分割的citys，通常teacher要比student好的
- 还有一种情况，就是训练并不充分，增大epoch，可能会继续涨点（特别是citys上）。因为teacher只不过是ema，数学上看最终student和teacerh应该要converge要相同的情况。

我其实个人角度，是偏向随机优化中的expoloitation and exploration 来理解的。student就是去explore更好的结果(当然有好有坏)，然后teacher稳定住不要一下子变化太大（特别对那种worse的updatinng的情况）。

其实这也是一个research direction。改进这种naive的teacher student结构，如何给一个更好的teacher呢？值得玩一下

**Comment by jjjsyyy** [comment]
十分感谢！您的答复非常详细❤❤
